# Generated by Django 4.2.20 on 2025-04-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('room_number', models.CharField(max_length=10)),
                ('length_of_stay', models.CharField(choices=[('1 Night', '1 Night'), ('2-5 Nights', '2-5 Nights'), ('6+ Nights', '6 or More Nights')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StayPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('Business', 'Business'), ('Tourist', 'Tourist'), ('Conference', 'Conference'), ('Visiting', 'Visiting'), ('Other', 'Other')], max_length=20)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_purposes', to='questionnaire.guest')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('happy', '😊'), ('neutral', '😐'), ('sad', '😞')], max_length=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_responses', to='questionnaire.guest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.satisfactionquestion')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questionnaire.guest')),
            ],
        ),
    ]
